### PR TITLE
Correctly parse Metaclasses

### LINKED ISSUE #246: Error reading files when parsing python metaclass
My autoapi_dir only contains a file :
```
class Meta(type):
    def __init__(self):
        pass
```

And my `conf.py` only contains:
```
extensions = [
    "autoapi.extension",
]
...
```
When I run `sphinx-build sourcedir outdir`, I got an error saying 
```
WARNING: Error reading file
```

### PR DESCRIPTION
**Pull request by ashb**
Fixes #246

### CODE REVIEW

**Comment by ashb** [comment]
@AWhetter If you have a spare moment to check, this turned out to be an easy fix.

**Review by AWhetter — APPROVED** [review]
Sorry it's taken me so long to get around to looking at this.
It looks great to me. Thanks for the fix!

**Comment by ashb** [comment]
@AWhetter No worries, I entirely understand the life of an open-source maintainer :)

**Comment by ashb** [comment]
@AWhetter Any chance we could get a 1.5.2/1.6.0 release?

**Pull request merged**
