### PR TITLE
Add version information

### LINKED ISSUE #197: __version__ or version_info?
Could you add any form of version information to the module. This allows for adding options based on the autoapi version.

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Add `__version__` to the module.

Maybe be better to convert to a single source of the version number, see https://packaging.python.org/guides/single-sourcing-package-version/. But this should be a separate PR IMO.

Fixes #197

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Travis fails on `3.8`, but this also happens on master if you run it today, https://travis-ci.com/github/MatthijsBurgh/sphinx-autoapi/jobs/323789875

**Comment by MatthijsBurgh** [comment]
@AWhetter ping ;)

**Comment by MatthijsBurgh** [comment]
@AWhetter pingping ;)

**Comment by AWhetter** [comment]
Thanks for the implementation!

**Pull request merged**
